# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=10)),
                ('out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
